services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodle
    restart: always
    ports:
      - 8989:80
    env_file:
      - .env
    volumes:
      - moodle_data:/var/www/moodledata
      - moodle_html:/var/www/html
    networks:
      - moodle_net

  mariadb:
    image: mariadb:10.11
    container_name: moodle-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MOODLE_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${MOODLE_DATABASE_NAME}
      MYSQL_USER: ${MOODLE_DATABASE_USER}
      MYSQL_PASSWORD: ${MOODLE_DATABASE_PASSWORD}
    command: --max_allowed_packet=256M --innodb_buffer_pool_size=512M
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - moodle_net

volumes:
  moodle_html:
  moodle_data:
  mariadb_data:

networks:
  moodle_net:
    driver: bridge
